name: mateapp
description: Mate App - Dev

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

  # for Statemanagement
  provider: ^4.1.3

  # Firebase Dependencies
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  firebase_analytics: ^6.0.0
  cloud_firestore: ^0.14.0+1
  firebase_crashlytics: ^0.1.4+1

  # Other dependencies
  timeago: ^2.0.26
  intl: ^0.16.1
  font_awesome_flutter: ^8.2.0
  url_launcher: ^5.5.0
  pie_chart: ^3.1.1
  flutter_markdown: ^0.4.3
  shared_preferences: ^0.5.10
  flutter_launcher_icons: "^0.7.3"
  # Plattform aware widgets
  flutter_platform_widgets: ^0.60.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.2.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon_50.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/welcomescreen.png