name: Check if App builds properly

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  java_version: "12.x"
  flutter_version: "1.20.4"

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        env:
          cache-name: flutter-cache
        with: 
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - name: install dependencies
        run: flutter pub get
        
  lint:
    needs: setup
    runs-on: macos-latest
    steps: 
      - name: lint
        run: flutter analyze
  
  build_android:
    needs: setup
    runs-on: macos-latest
    steps:
      - name: Decode google-services.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > android/app/src/prod/google-services.json
      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        env:
          cache-name: flutter-cache
        with: 
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      - run: flutter build apk --flavor prod
        
  build_ios:
    needs: setup
    runs-on: macos-latest
    steps:
      - name: Decode GoogleService-Info.plist
        env:
          FIREBASE_CONFIG_IOS: ${{ secrets.FIREBASE_CONFIG_IOS }}
        run: echo $FIREBASE_CONFIG_IOS > ios/Runner/GoogleService-Info.plist
      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        env:
          cache-name: flutter-cache
        with: 
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      - run: flutter build ios --release --no-codesign --flavor prod
