name: Check if App builds properly

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  java_version: "12.x"
  flutter_version: "1.20.4"
  FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
  FIREBASE_CONFIG_IOS: ${{ secrets.FIREBASE_CONFIG_IOS }}

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        env:
          cache-name: flutter-cache
        with: 
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - name: install dependencies
        run: flutter pub get
        
  lint:
    needs: setup
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        env:
          cache-name: flutter-cache
        with: 
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - name: lint
        run: flutter analyze
  
  code_coverage:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.jave_version }}
      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        env:
          cache-name: flutter-cache
        with: 
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - name: remove old helper file
        run: rm test/coverage_helper_test.dart
      - name: create file to write to
        run: file=test/coverage_helper_test.dart
      - name: create file with untested dart files
        run: 'find lib -name "*.dart" | cut -c4- | awk -v package=mateapp "{printf "// ignore: unused_import \n import '\''package:%s%s'\'';\n", package, $1}" >> $file;'
      - name: create main function in file
        run: echo "void main(){}" >> $file
      - name: Create Code Coverage Report
        run: flutter test --coverage
      - name: upload to codecov.io
        run: bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info -t ${{ secrets.CODECOV_TOKEN }}
        shell: bash

  build_android:
    needs: setup
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Decode google-services.json
        run: mkdir android/app/src/prod && echo '${{ env.FIREBASE_CONFIG }}' > android/app/google-services.json
        shell: bash
      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        env:
          cache-name: flutter-cache
        with: 
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - name: install dependencies and build apk
        run: flutter pub get && flutter build apk --flavor prod
        
  build_ios:
    needs: setup
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Decode GoogleService-Info.plist
        run: mkdir -p ios/config/prod && echo '${{ env.FIREBASE_CONFIG_IOS }}' > ios/config/prod/GoogleService-Info.plist

        shell: bash
      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        env:
          cache-name: flutter-cache
        with: 
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - name: install dependencies and build for ios
        run: flutter pub get && flutter build ios --release --no-codesign --flavor prod